apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: cbuto/django-app-jenkins:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80

