sudo: required

language: python

notifications:
  email: false

services:
  - docker

os:
- linux

env:
  global:
    - DOCKER_IMAGE_NAME="django-app-travis"
    - K8S_DEPLOYMENT_NAME="django-app"

before_script:
- sudo apt-get -qq update
- sudo apt-get install postgresql -y
- pip install -r config/requirements.pip
- docker pull cbuto/kubectl
- docker pull ${DOCKER_USERNAME}/django-app-travis
- docker pull cbuto/django-postgres:v1
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

script:
- docker run -d --name db cbuto/django-postgres:v1
- docker run -d --name django-app ${DOCKER_USERNAME}/django-app-travis
- export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' db)
- docker exec django-app sed -i "s/database.default.svc.cluster.local/$IP/g" django_app/settings.py
- docker exec django-app bash -c "cd ../scripts &&  chmod +x wait-for-postgres.sh"
- docker exec django-app bash -c "cd ../scripts && ./wait-for-postgres.sh $IP 5432"
- coverage run django-app/manage.py test -v 2

after_success:
- coveralls
- docker build -t ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID} .
- docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
- docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
- docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
- sed -i -e 's|KUBE_CA_CERT|'"${KUBE_CA_CERT}"'|g' kubeconfig
- sed -i -e 's|KUBE_ENDPOINT|'"${KUBE_ENDPOINT}"'|g' kubeconfig
- sed -i -e 's|KUBE_ADMIN_CERT|'"${KUBE_ADMIN_CERT}"'|g' kubeconfig
- sed -i -e 's|KUBE_ADMIN_KEY|'"${KUBE_ADMIN_KEY}"'|g' kubeconfig
- sed -i -e 's|KUBE_USERNAME|'"${KUBE_USERNAME}"'|g' kubeconfig
- docker run -v ${TRAVIS_BUILD_DIR}:/kube cbuto/kubectl kubectl --kubeconfig /kube/kubeconfig set image deployment/${K8S_DEPLOYMENT_NAME} ${K8S_DEPLOYMENT_NAME}=${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:$TRAVIS_BUILD_ID
