apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: database
    spec:
      containers:
        - name: postgres
          image: cbuto/django-postgres:v1
          imagePullPolicy: Always
          env:
          ports:
            - containerPort: 5432

